config/routes.rb
Illusion::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get "browse/timeline"
  get "browse/users"
  get "browse/articles"
  get 'browse/groups'
  get "articles/search"
  root to: "users#index"
  get 'users/followers'
  get 'users/followed'
  get 'users/unique'
  get 'users/cover'
  get 'api/get_user'
  get 'api/get_user_avatar'
  get 'api/get_my_articles'
  get 'api/get_article_image'
  get 'api/get_followers'
  get 'api/get_all_users'
  get 'api/get_user_articles'
  get 'api/get_fullname'
  get 'api/get_article_comments'

  resources :dashboard

  scope controller: :terms, path: 'lead' ,only: [] do
    get :eula
  end

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users, only: [:show, :index], shallow: true

  resources :articles
  resources :follows, only: [:create, :destroy]
  resources :comments
  resources :groups, path_names: { root: 'my' }


  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users do
    member do
      match :follow, via: [:get, :post]
      match :unfollow, via: [:get, :post]
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :messages

  resources :messages, only: [] do
    scope controller: :messages do
      member do
        match :mark_as_read, via: [:get, :post]
      end
    end
  end

  resources :articles, only: [] do
    scope controller: :articles do
      member do
        match :share_via_message, via: [:get, :post]
      end
    end
  end

  resources :groups do
    scope controller: :groups do
      member do
        match :add_article_to, via: [:get, :post]
        match :delete_article_from, via: [:get, :post]
      end
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  include Logable
  mount_uploader :photo, ArticlePhotoUploader

  belongs_to :user
  belongs_to :group
  has_many :comments, class_name: 'Comment', foreign_key: 'article_id'
  has_many :views, foreign_key: "article_id", dependent: :destroy
  has_many :viewers, through: :views

  validates :category, presence: true
  validates :theme, presence: true
  validates :content, presence: true

  extend FriendlyId
  friendly_id :theme

  def print_info
    p "#{self.theme} - #{self.content} at #{self.date.strftime('%d %B %Y')} by #{User.find(self.user_id)}"
  end

  def self.search(search)
    if search
      self.where('lower(theme) LIKE ?', "%#{search}%")
    else
      self.all
    end
  end

  def to_param
    "#{self.id} #{self.theme} #{self.user_id}".parameterize
  end

  def return_created_at_as_nice_string
    self.created_at.strftime("%d %B %Y.")
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_article, only: [:show, :edit, :destroy, :update, :share_via_message]
  before_action :require_category, only: [:index, :edit, :new]
  before_action :can_submit, only: [:new, :edit]

  def index
  	@articles = current_user.user_articles.all
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
  end

  def create
  	@article = current_user.user_articles.create(article_params)
  	if @article.save
      @article.track_log(current_user)
      redirect_to @article
    else
      redirect_to :back, alert: "Theme and article content cannot be blank."
    end
  end

  def new
  	@article = current_user.user_articles.new
  end

  def show
    if user_signed_in? && !current_user.view?(@article) && @article.user != current_user
      view = current_user.view!(@article)
      view.track_log(current_user.id)
    end
    @status = 1
    @comments = @article.comments.all
    @comment = Comment.new
    @me = current_user == @article.user
  end

  def edit
    if !user_signed_in? || @article.user!= current_user
      redirect_to @article
    end
  end

  def destroy
    @article.reverse_logs
  	@article.destroy
  	redirect_to current_user
  end

  def update
    if @article.update(article_params_to_update)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def search
    @articles = Article.search(params[:search])
  end

  def share_via_message
    current_user.sent_messages.create!(theme: @article.theme, content: "#{current_user.first_name} shared article <br><a href='#{article_path(@article)}'>#{@article.theme}</a> to you", recipient_id: params[:user_id])
    respond_to do |format|
      format.js { render json: :success }
    end
  end

  private

  def article_params
  	params.require(:article).permit(:content, :date, :user_id, :theme, :category, :photo, :group_id)
  end

  def article_params_to_update
    params.require(:article).permit(:content, :date, :user_id, :theme, :category, :photo, :group_id)
  end

  def require_article
    @article = Article.find(params[:id])
  end

  def require_category
    @category = ["Programming", "Business", "Traveling", "Languages", "Cars", "Technologies", "Gaming", "Films", "Music", "Poetry", "News", "Wiki", "How To", "My Lifestyle", "Science", "Math", "Other"]
  end

  def can_submit
    if @article.present? && @article.theme.present? && @article.theme.length >= 2
      @can = true
    else
      @can = false
    end
  end

end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_add_to_group_modal.html.haml
#add_to_group.modal
  .modal-dialog
    .modal-content
      = form_for @article do |f|
        .modal-header
          Add article
          = link_to @article.theme, @article
          to group
        .modal-body
          - if @article.group_id != nil
            %h5.alert.alert-info
              %strong.text-warning Note!
              This article already in group
              = link_to Group.find(@article.group_id).name, Group.find(@article.group_id)
              = ". If you will add it to another group, it will be removed from current group!"
            %br
          - if current_user.groups.any?
            = f.label "Choose group"
            %br
            = f.select :group_id,  current_user.groups.map { |g| [g.name, g.id] }, class: "form-control"
          - else
            You have not any groups
          %br
          = link_to "New group", new_group_path
        .modal-footer
          %a.btn.btn-sm.btn-danger{"data-dismiss" => "modal"} Cancel
          = f.submit "OK", class: "btn btn-sm btn-success"

app/views/articles/_article.html.haml
= content_tag_for(:div, article, class: "row") do
  .post{style: 'position: relative'}
    .post-img-content{style: "background: url(#{article.photo.url}) no-repeat; background-position: center; background-size: cover;"}
      %span.post-title
        %b= article.theme
        %br
        - if !article.group.nil?
          %b= article.group.name
    .content
      .author
        By
        %b= article.user.fullname
        |
        %time= article.return_created_at_as_nice_string
      %div.post-content.pander-sm.text-center
        %strong.text-muted= article.content.empty? ? 'Looks like empty' : strip_tags(article.content)[0..80].html_safe
      %div
        .text-right{style: 'position:absolute;bottom:10px;right:10px'}
          %a.btn.btn-warning.btn-sm{href: article_path(article)}
            Continue reading&nbsp;
            %i.fa.fa-align-left
        - if params[:controller] == 'groups' && params[:action] == 'show' && user_signed_in? && article.user == current_user
          .pull-left= link_to "remove", delete_article_from_group_path(article: article), class: "btn btn-danger btn-default"

app/views/articles/_form_inputs.html.haml
= render 'paste_html'
%br
= form_for @article do |f|
  = f.hidden_field :group_id, value: params[:group_id] if params[:group_id].present?
  .main-article-pane
    - if @article.errors.any?
      .panel.panel-danger
        .panel-heading
          Errors
        .panel-body
          -@article.errors.full_messaes.each do |ue|
            %i.fa.fa-warning= "#{ue}"
    .text-right
      - if !current_page?(new_article_path)
        = link_to @article, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure want to delete article ' }  do
          %i.fa.fa-times
    %br
      = f.text_field :theme, placeholder: "Theme...", class: "article-theme",autocomplete: 'off' , style: "width: 100%;", value: (params[:theme].present? ? params[:theme] : @article.theme )
    %br
    .text-center= f.cktext_area :content, id: 'editor'
    %br
  .side-panel-article
    = button_tag(type: "submit", class: "orange-d2 pull-left") do
      %i.fa.fa-check.fa-lg= " Save"
    %button.gray-d2.pull-right{href: '#', data: { toggle: 'modal', target: '#paste_html' } }
      %i.fa.fa-code.fa-lg &nbsp;Paste html
    %br
    .container-dial
      %br
      %br
      .text-center= f.select :category, @category, included_blank: true, class: "styled-select"
      = f.file_field :photo, id: "file-input"
      %br
      %br
      .row
        .col-md-10.col-md-offset-1
          - if @article.photo?
            #imagee.get_cover= image_tag @article.photo.url, class: 'img-thumbnail'
          - else
            #imagee.get_cover
              .text-center.pander
                %i.fa.fa-5x.fa-upload
                %h3 Choose article cover image
          %br

app/views/articles/_full_screen.html.haml
#modal-full-screen.modal{"aria-hidden" => "true", role: "dialog", tabindex: "-1"}
  .modal-dialog.modal-full
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"}
          %i.fa.fa-compress.fa.lg
        %h4#myModalLabel.modal-title{align: "center"}= "#{@article.theme} (#{@article.category})"
      .modal-body
        = @article.content.html_safe

app/views/articles/_owner_links.html.haml
= link_to "EDIT", edit_article_path

app/views/articles/_paste_html.html.haml
#paste_html.modal
  .modal-dialog
    .modal-content
      .modal-header
        %h3 Paste your html code here
      .modal-body
        = text_area_tag :content, nil, class: 'form-control paste_html', placeholder: 'Paste html here', style:'height:264px'
        = check_box_tag :add_to_end, 'Add to end of html', id: 'to_the_end', checked: true
        = label_tag :add_to_end
      .modal-footer
        .text-right
          = link_to 'Paste', '#', class: 'paste_html_button btn btn-success'

app/views/articles/_share_via_message.html.haml
.modal#share_via_message
  .modal-dialog
    .modal-content
      .modal-body.text-center
        %h3 Share this article via private message
        with:
        %select#users_select
          - User.all.each do |user|
            %option{ value: user.id }= user.fullname
        %br
        %br
        .text-center
          %button.btn.btn-success.share_via_message Share

app/views/articles/edit.html.haml
- content_for :title, "Editing... #{@article.theme[0..10]}"
= render 'form_inputs'

app/views/articles/index.html.haml
- content_for :title, "My Calendar"
= stylesheet_link_tag "calendar"
%a.btn.btn-primary.btn-sm{href: new_article_path} Create new Article
%div#calendar.small-8.large-centered.column
  %h2{align: "center"}
    = link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y/%m")
    #{@date.strftime("%B %Y")}
    = link_to ">", :month => (@date.end_of_month+1).strftime("%Y/%m")
  = calendar_for @articles, :year => @date.year, :month => @date.month do |calendar|
    = calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')
    = calendar.day(:day_method => :created_at) do |date, articles|
      = date.day
      - if date.to_s == Time.now.strftime("%Y-%m-%d")
        %br
        .text-center
          %a.btn.btn-primary.btn-sm{href: new_article_path, "data-toggle" => "tooltip", "data-placement" => "top", title: "Create new article"}
            %i.fa.fa-file-o
      %ul
        - for article in articles
          = link_to article, "data-toggle" => "tooltip", "data-placement" => "top", title: article.theme do
            = image_tag article.photo.small.url, class: "img-thumbnail"

app/views/articles/new.html.haml
- content_for :title, "New Article"
= render 'form_inputs'

app/views/articles/show.html.haml
- content_for :title, @article.theme[0..15]
= stylesheet_link_tag "comment"
= render "share_via_message"
- if @article.user == current_user
  = render "add_to_group_modal"
.page-header
  .row
    .col-xs-12.col-sm-6.col-md-8.animated.slideInLeft.verticalLine
      %div
        .text-right
          %button.close{href: "#", "data-target" => "#modal-full-screen", "data-toggle" => "modal"}
            %i.fa.fa-arrows-alt &nbsp; &nbsp;
          &nbsp;
          &nbsp;
          &nbsp;
          %button.close{href: "#", "data-target" => "#share_via_message", "data-toggle" => "modal"}
            %i.fa.fa-share &nbsp;&nbsp;
        %h1
          = "#{@article.theme} (#{@article.category})"
        %h4
          %em.text-muted
            by
            = link_to @article.user.fullname, @article.user
            %i.fa.fa-circle
            #{@article.created_at.strftime("%d %b %Y")}
            - if !@article.group.nil?
              %i.fa.fa-circle
              = link_to @article.group.name, @article.group
        .article-content #{@article.content.html_safe}
      %br
    .col-xs-6.col-md-4.animated.slideInRight
      %h4
        %strong viewed
        #{@article.views.count || 0} times
      - if @article.user == current_user
        = link_to edit_article_path, class: "btn btn-warning btn-sm" do
          %i.fa.fa-edit &nbsp;Edit
        #a.btn.btn-primary.btn-sm{ data: { toggle: "modal", target: "#add_to_group" } }
          %i.fa.fa-plus &nbsp;Add to group
        %br
        %br
      .thumbnail
        = image_tag @article.photo.url
      - if user_signed_in?
        = render 'comments/form'
      %br
      %div#unordered_list.all_comments
        #comments_count Comments(#{@article.comments.count})
        - @article.comments.order(created_at: :asc).each do |comment|
          = render 'comments/comment', comment: comment
= render 'users/articles'
= render "full_screen"