config/routes.rb
Illusion::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get "browse/timeline"
  get "browse/users"
  get "browse/articles"
  get 'browse/groups'
  get "articles/search"
  root to: "users#index"
  get 'users/followers'
  get 'users/followed'
  get 'users/unique'
  get 'users/cover'
  get 'api/get_user'
  get 'api/get_user_avatar'
  get 'api/get_my_articles'
  get 'api/get_article_image'
  get 'api/get_followers'
  get 'api/get_all_users'
  get 'api/get_user_articles'
  get 'api/get_fullname'
  get 'api/get_article_comments'

  resources :dashboard

  scope controller: :terms, path: 'lead' ,only: [] do
    get :eula
  end

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users, only: [:show, :index], shallow: true

  resources :articles
  resources :follows, only: [:create, :destroy]
  resources :comments
  resources :groups, path_names: { root: 'my' }


  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users do
    member do
      match :follow, via: [:get, :post]
      match :unfollow, via: [:get, :post]
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :messages

  resources :messages, only: [] do
    scope controller: :messages do
      member do
        match :mark_as_read, via: [:get, :post]
      end
    end
  end

  resources :articles, only: [] do
    scope controller: :articles do
      member do
        match :share_via_message, via: [:get, :post]
      end
    end
  end

  resources :groups do
    scope controller: :groups do
      member do
        match :add_article_to, via: [:get, :post]
        match :delete_article_from, via: [:get, :post]
      end
    end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :articles, class_name: "Article", foreign_key: "group_id"

  validates :name, presence: true

  def cover_photo
    articles.order(created_at: :asc).each do |article|
      if article.photo?
        return article.photo.small.url
      end
    end
    nil
  end

  def total_views
    views = 0
    articles.order(created_at: :asc).each do |article|
      views += article.views.count
    end
    views
  end

  def views
    views = []
    articles.order(created_at: :asc).each do |article|
      article.views.each do |view|
        views << view
      end
    end
    views
  end

  def comments
    comments = []
    articles.order(created_at: :asc).each do |article|
      article.comments.each do |comment|
        comments << comment
      end
    end
    comments
  end

  def self.search(search)
    if search
      self.where('lower(name) LIKE ?', "%#{search}%")
    else
      self.all
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
    @articles = current_user.user_articles if user_signed_in?
    @list = 0
    @today = @group.articles.where(created_at: (Time.now.beginning_of_day..Time.now.end_of_day))
  end

  def create
    @group = current_user.groups.create(group_params)
    if @group.save
      redirect_to @group, notice: "Group '#{@group.name}' was succesfully created"
    else
      redirect_to :back, alert: "Group cannot to be saved. Please try again."
    end
  end

  def add_article_to
    if params[:article]
      if @article = Article.find(params[:article]).update_columns(group_id: params[:id])
        flash[:notice] = "Successfully added..."
      end
    end
    redirect_to Group.find(params[:id])
  end

  def delete_article_from
    if params[:article]
      if @article = Article.find(params[:article]).update_columns(group_id: nil)
        flash[:notice] = "Successfully removed..."
      end
    end
    redirect_to Group.find(params[:id])
  end

  def update
  end

  def destroy
    @group = Group.find(params[:id])
    Article.where(group_id: @group.id).each do |article|
      article.update_column(:group_id, nil)
    end
    @group.destroy
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :description)
  end

end

app/views/groups/_add_article_modal.html.haml
#add_article_to_group.modal
  .modal-dialog
    .modal-content
      .modal-header
        Add articles to group
      .modal-body.text-center
        = link_to 'Create new', new_article_path(group_id: @group.id), class: 'btn btn-default btn-lg text-success'
        %br
        or Choose from existing articles
        %br Note! Articles may belong to another group! Be careful!
        .text-danger
        %br
        .form-inline
          %select#articles_select
            %option
            - @articles.each do |article|
              - if article.group != @group
                %option{ value: add_article_to_group_path(article: article) }= "#{article.theme}(#{article.group.nil? ? 'alone' : article.group.name})"
                - @list = @list + 1
          %br
          %br
          %a.btn.btn-success#add_to_group_submit{ href: '#' } ADD
        - if @list == 0
          %h3.text-muted You have not any articles, which you can add to this gruop, maybe they are here

app/views/groups/_admin_panel.html.haml
= link_to "add article", "#", class: "btn btn-default btn-xs", data: { toggle: "modal", target: "#add_article_to_group" }
= link_to "delete group", group, method: :delete,  class: "btn btn-danger btn-xs", "data-confirm" => "Really want to delete this group?"
/ .well
/   .row
/     .col-md-6 
/       %h3 Views
/       %ul.list-group
/         - group.views.each do |view|
/           %li.list-group-item
/             %h4
/               = "#{time_ago_in_words(view.created_at)} #{t('ago')}. on"
/               .label.label-success #{view.article.theme}
/     .col-md-6
/       %h3 Comments
/       %ul.list-group
/         - group.comments.each do |comment|
/           %li.list-group-item
/             %h4
/               = "#{time_ago_in_words(comment.created_at)} #{t('ago')}. on"
/               .label.label-success #{comment.article.theme}

app/views/groups/_group.html.haml
= content_tag_for(:div, group, class: 'panel panel-success group' ) do
  .panel-heading
    .row
      .col-md-6
        = image_tag group.cover_photo, class: 'img-circle'
        = group.name
      .col-md-6.vcenter
        .text-right= link_to 'More', group, class: 'btn btn-primary'
  .panel-body
    .row
      .col-md-6
        %strong.text-success Articles
        = group.articles.count
      .col-md-6
        .text-right
          %strong.text-success Views
          = group.total_views
    %div{style: "height: 2px; background-color: black; text-align: center;margin-bottom: 22px"}
      %span{style: "background-color: white; position: relative; top: -0.7em; padding: 20px;"}
        %strong About
    - if group.description.present?
      %strong.text-center
        %em.text-muted= "\"#{group.description}\""
    - else
      %em.text-muted.text-center
        User did not added description to this group
    - if group.articles.any?
      %br
      %strong
        .text-center.text-success last article
      .list-group-item.list-group-item-success
        = image_tag group.articles.last.photo.small.url, class: 'img-circle'
        = link_to group.articles.last.theme, group.articles.last
  .panel-footer
    .pull-left
      .text-muted= "#{time_ago_in_words(group.created_at)} ago."
    .text-right
      by
      = link_to group.user.fullname, group.user

app/views/groups/index.html.haml
%h1
  My groups(#{current_user.groups.count})
  = link_to "Create new", new_group_path, class: "btn btn-sm btn-success"
- if current_user.groups.any?
  .row
    - current_user.groups.each do |group|
      .col-md-4= render 'groups/group', group: group
- else
  %h1 You have not any groups
  = link_to "Create", new_group_path

app/views/groups/new.html.haml
.pander-sm
  .text-center
    %h2
      Create new group&nbsp;
      %i.fa.fa-briefcase.text-danger
    %h4
      %em.text-danger and organize your articles more easier
  .row
    .well.col-md-8.col-md-offset-2
      = form_for @group do |f|
        = f.text_field :name, class: "form-control", placeholder: "Give your new group name"
        %br
        = f.text_area :description, class: "form-control", placeholder: "Put some description here"
        %br
        .text-right= f.submit "Continue", class: "btn btn-success btn-sm"

app/views/groups/show.html.haml
.pander-sm
  .text-center
    %h1
      = @group.name
      %br
    - if user_signed_in? && @group.user == current_user
      = render 'admin_panel', group: @group
  %h4.text-center
    %em.text-muted= @group.description
  %h5.text-center
    %em.text-muted
      by
      = link_to @group.user.fullname, @group.user
      %i.fa.fa-circle
      #{@group.created_at.strftime("%d %b %Y")}
  %hr
  %h1.text-center
    Articles
    .label.label-success= @group.articles.count
    Today
    .label.label-success= @today.count
  .row
    - @group.articles.each do |article|
      .col-md-4
        = render "articles/article", article: article
= render "add_article_modal" if user_signed_in?