config/routes.rb
Illusion::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get "browse/timeline"
  get "browse/users"
  get "browse/articles"
  get 'browse/groups'
  get "articles/search"
  root to: "users#index"
  get 'users/followers'
  get 'users/followed'
  get 'users/unique'
  get 'users/cover'
  get 'api/get_user'
  get 'api/get_user_avatar'
  get 'api/get_my_articles'
  get 'api/get_article_image'
  get 'api/get_followers'
  get 'api/get_all_users'
  get 'api/get_user_articles'
  get 'api/get_fullname'
  get 'api/get_article_comments'

  resources :dashboard

  scope controller: :terms, path: 'lead' ,only: [] do
    get :eula
  end

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users, only: [:show, :index], shallow: true

  resources :articles
  resources :follows, only: [:create, :destroy]
  resources :comments
  resources :groups, path_names: { root: 'my' }


  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users do
    member do
      match :follow, via: [:get, :post]
      match :unfollow, via: [:get, :post]
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :messages

  resources :messages, only: [] do
    scope controller: :messages do
      member do
        match :mark_as_read, via: [:get, :post]
      end
    end
  end

  resources :articles, only: [] do
    scope controller: :articles do
      member do
        match :share_via_message, via: [:get, :post]
      end
    end
  end

  resources :groups do
    scope controller: :groups do
      member do
        match :add_article_to, via: [:get, :post]
        match :delete_article_from, via: [:get, :post]
      end
    end
  end
end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController

  def index
    @comments = Comment.order(created_at: :desc)
  end

  def timeline
    @logs = Log.order(created_at: :desc)
    respond_to do |format|
      format.html { current_user.read_news! }
      format.json { render text: current_user.has_new_logs? }
    end
  end

  def articles
    @articles = Article.search(params[:search]).order(created_at: :desc).paginate(page: params[:page], per_page: 9)
  end

  def users
    @users = User.search(params[:search]).order(updated_at: :desc).paginate(page: params[:page], per_page: 9)
  end

  def groups
    @groups = Group.search(params[:search]).order(created_at: :desc).paginate(page: params[:page], per_page: 9)
  end
end

app/helpers/browse_helper.rb
module BrowseHelper
end

app/views/browse/_nav_links.html.haml
.row
  .col-md-offset-3
    .row
      .col-md-3
        .row
          = link_to  browse_articles_path(search: params[:search]), class: "btn btn-default btn-block btn-browse-exp #{'active-def-btn' if params[:action] == 'articles'}" do
            %h4= t('Articles')
      .col-md-3
        .row
          = link_to browse_users_path(search: params[:search]), class: "btn btn-default btn-block btn-browse-exp #{'active-def-btn' if params[:action] == 'users'}" do
            %h4= t('Users')
      .col-md-3
        .row
          = link_to browse_groups_path(search: params[:search]), class: "btn btn-default btn-block btn-browse-exp #{'active-def-btn' if params[:action] == 'groups'}" do
            %h4= t('Groups')

app/views/browse/_new_article.html.haml
= content_tag_for(:li, logable, user, class: 'animated rotateInUpLeft timeline-inverted' ) do
  .timeline-badge.default
    %i.fa.fa-lg.fa-bolt
  .timeline-panel
    .timeline-body
      %h3{style: 'margin-top:0px;'}= t('New_article_event')
      .pander
        = link_to logable.user do
          = image_tag logable.user.avatar.small.url, class: 'img-circle'
          = logable.user.fullname
        = t('created_new_article')
        = link_to logable.theme, logable
        %em.text-muted= "#{time_ago_in_words(logable.created_at)} #{t('ago')}."

app/views/browse/_new_comment.html.haml
= content_tag_for(:li, logable, user, class: 'animated rotateInUpRight' ) do
  .timeline-badge.primary
    %i.fa.fa-lg.fa-comment
  .timeline-panel
    .timeline-body
      %h3{style: 'margin-top:0px;'}= t('New_comment_event')
      .pander
        = link_to logable.user do
          = image_tag logable.user.avatar.small.url, class: 'img-circle'
          = logable.user.fullname
        = t('commented_your_article')
        = link_to logable.article.theme, logable.article
        %em.text-muted= "#{time_ago_in_words(logable.created_at)} #{t('ago')}."

app/views/browse/_new_relationship.html.haml
= content_tag_for(:li, logable, user, class: 'animated rotateInUpRight' ) do
  .timeline-badge.danger
    %i.fa.fa-lg.fa-users
  .timeline-panel
    .timeline-body
      %h3{style: 'margin-top:0px;'}= t('New_follower_event')
      .pander
        = link_to logable.follower do
          = image_tag logable.follower.avatar.small.url, class: 'img-circle'
          = logable.follower.fullname
        = t('followed_you')
        %em.text-muted= "#{time_ago_in_words(logable.created_at)} #{t('ago')}."

app/views/browse/_new_view.html.haml
= content_tag_for(:li, logable, user,  class: 'animated rotateInUpLeft timeline-inverted' ) do
  .timeline-badge.warning
    %i.fa.fa-lg.fa-eye
  .timeline-panel
    .timeline-body
      %h3{style: 'margin-top:0px;'}= t('New_view_event')
      .pander
        = link_to user do
          = image_tag user.avatar.small.url, class: 'img-circle'
          = user.fullname
        = t('read_your_article')
        = link_to logable.article.theme, logable.article
        %em.text-muted= "#{time_ago_in_words(logable.created_at)} #{t('ago')}."

app/views/browse/articles.html.haml
= render 'nav_links'
.row
  .col-md-6
    .digg_pagination= will_paginate @articles
  .col-md-6
    %br
    .form-inline.pull-right
      = form_tag browse_articles_path, method: 'get', class: 'navbar-search pull-left' do
        = text_field_tag :search, params[:search], class: "form-control", placeholder: "Search articles"
        = button_tag(type: 'submit', class: "btn btn-primary") do
          %i.fa.fa-search.fa.lg.fa-inverse &nbsp;Search
- if @articles.any?
  .row.pander
    - @articles.each do |article|
      .col-md-4= render 'articles/article', article: article
- else
  %h3.text-center There are no articles mathes "#{params[:search]}"

app/views/browse/groups.html.haml
= render 'nav_links'
.row
  .col-md-6
    .digg_pagination= will_paginate @groups
  .col-md-6
    %br
    .form-inline.pull-right
      = form_tag browse_groups_path, method: 'get', class: 'navbar-search' do
        = text_field_tag :search, params[:search], class: "form-control", placeholder: "Search groups"
        = button_tag(type: 'submit', class: "btn btn-primary") do
          %i.fa.fa-search.fa.lg.fa-inverse
          &nbsp;Search
%br
.row
  - if @groups.any?
    - @groups.each do |group|
      .col-md-4= render "groups/group", group: group
  - else
    %h3.text-center There are no groups mathes "#{params[:search]}"

app/views/browse/timeline.html.haml
- content_for :title,  "Timeline"
= stylesheet_link_tag "timeline"
- count = 0
%ul.timeline
  - @logs.each do |log|
    - if log.logable_type == 'Article'
      - if !current_user.following?(log.logable.user).nil? && current_user.following?(log.logable.user).created_at < log.logable.created_at
        = render "new_article", logable: log.logable, user: log.user
        - count = count + 1
    - else
      - if log.get_recipient == current_user
        = render "new_#{log.logable_type.downcase}", logable: log.logable, user: log.user
        - count = count +1
- if count == 0
  .text-center
    %i.fa.fa-frown-o.fa-5x
  %h1.text-center.text-center No any news, which you able to see
  %h3.text-center
    Start
    = link_to 'creating articles', new_article_path
    and
    = link_to 'following users', browse_users_path
    to watch the news

app/views/browse/users.html.haml
= render 'nav_links'
.row
  .col-md-6
    .digg_pagination= will_paginate @users
  .col-md-6
    %br
    .form-inline.pull-right
      = form_tag browse_users_path, method: 'get', class: 'navbar-search' do
        = text_field_tag :search, params[:search], class: "form-control", placeholder: "Search users"
        = button_tag(type: 'submit', class: "btn btn-primary") do
          %i.fa.fa-search.fa.lg.fa-inverse
          &nbsp;Search
.row
  - if @users.any?
    - @users.each do |user|
      .col-md-4= render "users/user", user: user
  - else
    %h3.text-center There are no users mathes "#{params[:search]}"