config/routes.rb
Illusion::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get "browse/timeline"
  get "browse/users"
  get "browse/articles"
  get 'browse/groups'
  get "articles/search"
  root to: "users#index"
  get 'users/followers'
  get 'users/followed'
  get 'users/unique'
  get 'users/cover'
  get 'api/get_user'
  get 'api/get_user_avatar'
  get 'api/get_my_articles'
  get 'api/get_article_image'
  get 'api/get_followers'
  get 'api/get_all_users'
  get 'api/get_user_articles'
  get 'api/get_fullname'
  get 'api/get_article_comments'

  resources :dashboard

  scope controller: :terms, path: 'lead' ,only: [] do
    get :eula
  end

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users, only: [:show, :index], shallow: true

  resources :articles
  resources :follows, only: [:create, :destroy]
  resources :comments
  resources :groups, path_names: { root: 'my' }


  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users do
    member do
      match :follow, via: [:get, :post]
      match :unfollow, via: [:get, :post]
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :messages

  resources :messages, only: [] do
    scope controller: :messages do
      member do
        match :mark_as_read, via: [:get, :post]
      end
    end
  end

  resources :articles, only: [] do
    scope controller: :articles do
      member do
        match :share_via_message, via: [:get, :post]
      end
    end
  end

  resources :groups do
    scope controller: :groups do
      member do
        match :add_article_to, via: [:get, :post]
        match :delete_article_from, via: [:get, :post]
      end
    end
  end
end

app/views/layouts/_bottom.html.haml
.navbar.navbar-default.navbar-fixed-bottom
  %div{align: "center"}
    .label.label-success Cillusion 2013-2014
    %i.fa.fa-globe.fa-inverse= "All Rights Reserved"

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .row
      .col-md-4
        .container
          %h3 Terms
          = link_to 'Terms of use(eula)', '/terms/eula'
          %br
          = link_to 'Webservice', '#'
          %br
          = link_to 'How to use', '#'
          %br
          = link_to 'About', '#'
      .col-md-4
        .container
          %h3 Cooperation
          = link_to 'I am programmer', '#'
          %br
          = link_to 'I am businessman', '#'
          %br
          = link_to 'Make suggestion', '#'
      .col-md-2
        .container
          %h3 Feedback
          = link_to 'Leave feedback', '#'
          %br
          = link_to 'Contact with developers', '#'
      .col-md-2
        %h2 Cillusion
        %strong.text-center Vitaliy Krushelnitskiy
        %h4 2013-2014&copy;

app/views/layouts/_top.html.haml
.navbar.navbar-default.navbar-fixed-top
  .animated.fadeIn
    .navbar-header
      %a.navbar-brand{ href: root_path }
        = image_tag "logo-toolbar.png", height: '48px'
    .container-fluid
      %button.navbar-toggle{'data-toggle' => 'collapse', 'data-target' => '.NAVCOl', style: 'margin-top:-30px;'}
        %i.fa.fa-bars
      .collapse.navbar-collapse.NAVCOl
        .nav.navbar-left.navbar-nav
          - if user_signed_in?
            %li.nav-btn{"data-toggle" => "tooltip", "data-placement" => "bottom", title: t("Browse_website")}
              = link_to browse_articles_path do
                .rounded-btn.animated.browse-btn.bounceInDown
                  %i.fa.fa-book.fa-2x
            %li.nav-btn{"data-toggle" => "tooltip", "data-placement" => "bottom", title: t('Timeline')}
              = link_to browse_timeline_path do
                .rounded-btn.timeline-btn.animated.bounceInDown
                  %i.fa.fa-clock-o.fa-2x
                  #span.new_logs
                    %i.fa.fa-circle.text-danger
            %li.headerDivider
            %li.nav-btn{"data-toggle" => "tooltip", "data-placement" => "bottom", title: t('Messages')}
              =link_to messages_path do
                .rounded-btn.messages-btn.animated.bounceInDown
                  %i.fa.fa-envelope.fa-2x
                  #span.new_messages= current_user.unread_messages
            %li.nav-btn{"data-toggle" => "tooltip", "data-placement" => "bottom", title: t("Groups")}
              = link_to groups_path do
                .rounded-btn.groups-btn.animated.bounceInDown
                  %i.fa.fa-briefcase.fa-2x
            %li
              = form_tag browse_articles_path, method: 'get', style: "margin-top:20px;" do
                = text_field_tag :search, params[:search], class: "nav-search form-control", placeholder: t('search')
        .nav.navbar-right.navbar-nav.animated.bounceInRight
          -if user_signed_in?
            %li.nav-btn
              %a.dropdown-toggle{ href: "#", data: { toggle: 'dropdown' } }
                .rounded-btn.new_article-btn{ data: { help: current_user.user_articles.any? ? 'no' : 'yes' } }
                  %i.fa.fa-plus.text.fa-2x
              %ul.dropdown-menu
                .pander.text-center
                  %li
                    = link_to new_article_path, class: 'btn btn-default btn-lg' do
                      %i.fa.fa-book.text-success &nbsp;&nbsp;#{t('Article')}
                  %br
                  %li
                    = link_to new_group_path, class: 'btn btn-default btn-lg' do
                      %i.fa.fa-briefcase.text-danger &nbsp;&nbsp;#{t('Group')}
            %li.dropdown.nav-btn
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                = image_tag current_user.avatar.small.url, class: 'img-circle', width: '48px'
                = current_user.first_name
                %b.caret
              %ul.dropdown-menu
                - if current_user.is_admin?
                  %li
                    = link_to dashboard_index_path do
                      %i.fa.fa-home= t('Dashboard')
                %li
                  = link_to current_user do
                    %i.fa.fa-home= t('My_account')
                %li
                  = link_to edit_user_registration_path(current_user) do
                    %i.fa.fa-gear= " #{t('Account_settings')}"
                %li
                  = link_to articles_path do
                    %i.fa.fa-calendar= " #{t('My_calendar')}"
                %li
                  = link_to destroy_user_session_path, method: :delete do
                    %i.fa.fa-times= " #{t('Sign_out')}"
          -else
            %li
              .sign_up
                %a.sign_up{href: new_user_session_path} Sign up
                = link_to user_omniauth_authorize_path('facebook'), class: 'btn btn-primary btn-sm' do
                  %i.fa.fa-facebook.ga-lg

app/views/layouts/_video.html.haml
#modal-video.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog.modal-video
    .modal-content
      .modal-body
        %div{align: "center"}
          <iframe width="640" height="390" src="//www.youtube.com/embed/_gUatp_9NHc" frameborder="0" allowfullscreen></iframe>

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    <meta name="google-site-verification" content="9B073HFTIXTPZP-W983VqQhCgu_FRNLL-alCsRPZOUw" />
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-52714056-1', 'auto');
      ga('send', 'pageview');
    %meta{charset: "utf-8"}
    %title= "#{yield(:title)} cillusion"
    = stylesheet_link_tag  "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
  %body
    - if !user_signed_in? || !current_user.paused
      = render "layouts/top"
    %div#divq
      - if yield(:title) == "Main"
        .row
          #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
            %ol.carousel-indicators
              %li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
              %li{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}
              %li{"data-slide-to" => "2", "data-target" => "#carousel-example-generic"}
            .carousel-inner
              .item.active
                %img{alt: "First slide", src: "#{asset_path '4.jpg'}"}/
                .header-text.hidden-xs
                  .col-md-12.text-center
                    %h2
                      %span
                        = t('welcome_text')
                        %strong CILLUSION
                    %br
                    %h3
                      %span If you are new in our website, register, or if else, login.
                    %br
                    %div
                      %a.btn.btn-theme.btn-sm.btn-min-block{href: new_user_session_path} Login
                      %a.btn.btn-theme.btn-sm.btn-min-block{href: new_user_registration_path} Register
              .item
                %img{alt: "Second slide", src: "#{asset_path '2.jpg'}"}/
                .header-text.hidden-xs
                  .col-md-12.text-center
                    %h2
                      %span
                        Don't know, what is
                        %strong CILLUSION
                        ?
                    %br
                    %h3
                      %span Use info links below.
                    %br
                    %div
                      %a.btn.btn-theme.btn-sm.btn-min-block{href: "#", data: { toggle: "modal", target: "#modal-video" } } Info video
                      %a.btn.btn-theme.btn-sm.btn-min-block{href: "http://illusion.wikia.com/wiki/Main_Page"} Wiki
              .item
                %img{alt: "Third slide", src: "#{asset_path '3.jpg'}"}/
                .header-text.hidden-xs
                  .col-md-12.text-center
                    %h2
                      %span Have any ideas
                    %br
                    %h3
                      %span To make better Cillusion together.
                    %br
                    %div
                      %a.btn.btn-theme.btn-sm.btn-min-block{href: "mailto:embox@ukr.net"} Send feedback to developer
            %a.left.carousel-control{"data-slide" => "prev", href: "#carousel-example-generic"}
              %span.fa.fa-angle-left.glyphicon.icon-prev
            %a.right.carousel-control{"data-slide" => "next", href: "#carousel-example-generic"}
              %span.fa.fa-angle-right.glyphicon.icon-next
        = yield
      - else
        -if flash.each.count > 0
          - flash.each do |name, msg|
            - if msg.class == Array
              - msg.each do |message|
                = js add_gritter("#{msg}", title: name)
            - else
              - if flash[:notice]
                - title = 'Notification'
                - image = '/assets/notice.png'
              - else
                - title = 'Error'
                - image = '/assets/warning.png'
              = js add_gritter("#{msg}", image: image, title: title)
        %br
        %div{  class: "#{'container' if !['new', 'edit'].include?(params[:action]) }"  }
          - if !user_signed_in? || !current_user.paused
            = yield
          - else
            .row
              .col-md-3
                = link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary btn-block"
                %br
                %br
                = form_for current_user do |f|
                  = f.hidden_field :paused, value: :false
                  = f.submit "Restore profile", class: "btn btn-success btn-block"
              %h1.text-muted.col-md-9.pander Your profile was suspeded
      - if !user_signed_in?
        = render 'layouts/video'

app/views/layouts/batman.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Illusion</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "illusion" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div data-yield="main"></div>

<script type="text/javascript">
  Illusion.run();
</script>

</body>
</html>

app/views/layouts/dashboard.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
    %title= "#{yield(:title)} cillusion"
    = stylesheet_link_tag  "admin"
    = javascript_include_tag "admin"
    = csrf_meta_tag
  %body
    = render 'dashboard/top'
    %hr
    .container
      = yield